package Datos;

import java.util.ArrayList;
import modelo.Departamento;
import modelo.Kiosco;
import modelo.Municipio;
import modelo.Region;
import modelo.Usuario;

public class AlmacenamientoDeDatos {

    public static int numeroFactura;
    public static int codigoUsuarioActual;
    public static int paquetesEnviados;
    public static double ingresosTotales;
    public static ArrayList<Usuario> usuarios = new ArrayList<>();
    public static ArrayList<Region> regiones = new ArrayList<>();
    public static ArrayList<Departamento> departamentos = new ArrayList<>();
    public static ArrayList<Municipio> municipios = new ArrayList<>();
    public static ArrayList<Kiosco> kioscos = new ArrayList<>();

    public void llenarDepartamentosRegiones() {
        regiones.add(new Region("M", "Metropolitana", 35.00, 25.00, 0, 0));
        regiones.add(new Region("NT", "Norte", 68.50, 45.55, 0, 0));
        regiones.add(new Region("NO", "Nororiente", 58.68, 35.48, 0, 0));
        regiones.add(new Region("SO", "Suroriente", 38.68, 32.48, 0, 0));
        regiones.add(new Region("SOC", "Suroccidente", 34.00, 29.00, 0, 0));
        regiones.add(new Region("NOC", "Noroccidente", 44.50, 40.00, 0, 0));

        departamentos.add(new Departamento("SOC", "QTZ", "Quetzaltenango"));
        departamentos.add(new Departamento("SOC", "RTL", "Retalhuleu"));
        departamentos.add(new Departamento("SOC", "SNM", "San Marcos"));
        departamentos.add(new Departamento("SOC", "SLA", "Solola"));
        departamentos.add(new Departamento("SOC", "STZ", "Suchitepquez"));
        departamentos.add(new Departamento("SOC", "TCN", "Totonicapan"));
        departamentos.add(new Departamento("SOC", "ETL", "Escuintla"));
        departamentos.add(new Departamento("SOC", "STP", "Sacatepequez"));

        departamentos.add(new Departamento("M", "GTM", "Guatemala"));
        departamentos.add(new Departamento("M", "CHM", "Chimaltenango"));

        departamentos.add(new Departamento("NOC", "HUE", "Huhuetenango"));
        departamentos.add(new Departamento("NOC", "QUI", "Quiche"));

        departamentos.add(new Departamento("NT", "AVP", "Alta Verapaz"));
        departamentos.add(new Departamento("NT", "BVP", "Baja Verapaz"));
        departamentos.add(new Departamento("NT", "PTN", "Peten"));

        departamentos.add(new Departamento("SO", "JLP", "Jalapa"));
        departamentos.add(new Departamento("SO", "JTP", "Jutiapa"));
        departamentos.add(new Departamento("SO", "STR", "Santa Rosa"));

        departamentos.add(new Departamento("NO", "CQM", "Chiquimula"));
        departamentos.add(new Departamento("NO", "ELP", "El Progreso"));
        departamentos.add(new Departamento("NO", "IZA", "Izabal"));
        departamentos.add(new Departamento("NO", "ZAC", "Zacapa"));

        municipios.add(new Municipio("AVP", "0", "Cobán"));
        municipios.add(new Municipio("AVP", "1", "Santa Cruz Verapaz"));
        municipios.add(new Municipio("AVP", "2", "San Cristóbal Verapaz"));
        municipios.add(new Municipio("AVP", "3", "Tactic"));
        municipios.add(new Municipio("AVP", "4", "Tamahú"));
        municipios.add(new Municipio("AVP", "5", "San Miguel Tucurú"));
        municipios.add(new Municipio("AVP", "6", "Panzóz"));
        municipios.add(new Municipio("AVP", "7", "Senahú"));
        municipios.add(new Municipio("AVP", "8", "San Pedro Carchá"));
        municipios.add(new Municipio("AVP", "9", "San Juan Chamelco"));
        municipios.add(new Municipio("AVP", "10", "San Agustín Lanquín"));
        municipios.add(new Municipio("AVP", "11", "Santa María Cahabón"));
        municipios.add(new Municipio("AVP", "12", "Chisec"));
        municipios.add(new Municipio("AVP", "13", "Chahal"));
        municipios.add(new Municipio("AVP", "14", "Fray Bartolomé de las Casas"));
        municipios.add(new Municipio("AVP", "15", "Santa Catalina La Tinta"));
        municipios.add(new Municipio("AVP", "16", "Raxruhá"));
        municipios.add(new Municipio("BVP", "17", "Salamá"));
        municipios.add(new Municipio("BVP", "18", "San Miguel Chicaj"));
        municipios.add(new Municipio("BVP", "19", "Rabinal"));
        municipios.add(new Municipio("BVP", "20", "Cubulco"));
        municipios.add(new Municipio("BVP", "21", "Granados"));
        municipios.add(new Municipio("BVP", "22", "Santa Cruz el Chol"));
        municipios.add(new Municipio("BVP", "23", "San Jerónimo"));
        municipios.add(new Municipio("BVP", "24", "Purulhá"));
        municipios.add(new Municipio("CHM", "25", "Chimaltenango"));
        municipios.add(new Municipio("CHM", "26", "San José Poaquil"));
        municipios.add(new Municipio("CHM", "27", "San Martín Jilotepeque"));
        municipios.add(new Municipio("CHM", "28", "San Juan Comalapa"));
        municipios.add(new Municipio("CHM", "29", "Santa Apolonia"));
        municipios.add(new Municipio("CHM", "30", "Tecpán"));
        municipios.add(new Municipio("CHM", "31", "Patzún"));
        municipios.add(new Municipio("CHM", "32", "San Miguel Pochuta"));
        municipios.add(new Municipio("CHM", "33", "Patzicía"));
        municipios.add(new Municipio("CHM", "34", "Santa Cruz Balanyá"));
        municipios.add(new Municipio("CHM", "35", "Acatenango"));
        municipios.add(new Municipio("CHM", "36", "San Pedro Yepocapa"));
        municipios.add(new Municipio("CHM", "37", "San Andrés Itzapa"));
        municipios.add(new Municipio("CHM", "38", "Parramos"));
        municipios.add(new Municipio("CHM", "39", "Zaragoza"));
        municipios.add(new Municipio("CHM", "40", "El Tejar"));
        municipios.add(new Municipio("CQM", "41", "Chiquimula"));
        municipios.add(new Municipio("CQM", "42", "Jocotán"));
        municipios.add(new Municipio("CQM", "43", "Esquipulas"));
        municipios.add(new Municipio("CQM", "44", "Camotán"));
        municipios.add(new Municipio("CQM", "45", "Quezaltepeque"));
        municipios.add(new Municipio("CQM", "46", "Olopa"));
        municipios.add(new Municipio("CQM", "47", "Ipala"));
        municipios.add(new Municipio("CQM", "48", "San Juan Ermita"));
        municipios.add(new Municipio("CQM", "49", "Concepción Las Minas"));
        municipios.add(new Municipio("CQM", "50", "San Jacinto"));
        municipios.add(new Municipio("CQM", "51", "San José la Arada"));
        municipios.add(new Municipio("PTN", "52", "Flores"));
        municipios.add(new Municipio("PTN", "53", "San José"));
        municipios.add(new Municipio("PTN", "54", "San Benito"));
        municipios.add(new Municipio("PTN", "55", "San Andrés"));
        municipios.add(new Municipio("PTN", "56", "La Libertad"));
        municipios.add(new Municipio("PTN", "57", "San Francisco"));
        municipios.add(new Municipio("PTN", "58", "Santa Ana"));
        municipios.add(new Municipio("PTN", "59", "Dolores"));
        municipios.add(new Municipio("PTN", "60", "San Luis"));
        municipios.add(new Municipio("PTN", "61", "Sayaxché"));
        municipios.add(new Municipio("PTN", "62", "Melchor de Mencos"));
        municipios.add(new Municipio("PTN", "63", "Poptún"));
        municipios.add(new Municipio("ELP", "64", "El Jícaro"));
        municipios.add(new Municipio("ELP", "65", "Morazán"));
        municipios.add(new Municipio("ELP", "66", "San Agustín Acasaguastlán"));
        municipios.add(new Municipio("ELP", "67", "San Antonio La Paz"));
        municipios.add(new Municipio("ELP", "68", "San Cristóbal Acasaguastlán"));
        municipios.add(new Municipio("ELP", "69", "Sanarate"));
        municipios.add(new Municipio("ELP", "70", "Guastatoya"));
        municipios.add(new Municipio("ELP", "71", "Sansare"));
        municipios.add(new Municipio("QUI", "72", "Santa Cruz del Quiché"));
        municipios.add(new Municipio("QUI", "73", "Chiché"));
        municipios.add(new Municipio("QUI", "74", "Chinique"));
        municipios.add(new Municipio("QUI", "75", "Zacualpa"));
        municipios.add(new Municipio("QUI", "76", "Chajul"));
        municipios.add(new Municipio("QUI", "77", "Santo Tomás Chichicastenango"));
        municipios.add(new Municipio("QUI", "78", "Patzité"));
        municipios.add(new Municipio("QUI", "79", "San Antonio Ilotenango"));
        municipios.add(new Municipio("QUI", "80", "San Pedro Jocopilas"));
        municipios.add(new Municipio("QUI", "81", "Cunén"));
        municipios.add(new Municipio("QUI", "82", "San Juan Cotzal"));
        municipios.add(new Municipio("QUI", "83", "Santa María Joyabaj"));
        municipios.add(new Municipio("QUI", "84", "Santa María Nebaj"));
        municipios.add(new Municipio("QUI", "85", "San Andrés Sajcabajá"));
        municipios.add(new Municipio("QUI", "86", "Uspantán"));
        municipios.add(new Municipio("QUI", "87", "Sacapulas"));
        municipios.add(new Municipio("QUI", "88", "San Bartolomé Jocotenango"));
        municipios.add(new Municipio("QUI", "89", "Canillá"));
        municipios.add(new Municipio("QUI", "90", "Chicamán"));
        municipios.add(new Municipio("QUI", "91", "Ixcán"));
        municipios.add(new Municipio("QUI", "92", "Pachalum"));
        municipios.add(new Municipio("ETL", "93", "Escuintla"));
        municipios.add(new Municipio("ETL", "94", "Santa Lucía Cotzumalguapa"));
        municipios.add(new Municipio("ETL", "95", "La Democracia"));
        municipios.add(new Municipio("ETL", "96", "Siquinalá"));
        municipios.add(new Municipio("ETL", "97", "Masagua"));
        municipios.add(new Municipio("ETL", "98", "Tiquisate"));
        municipios.add(new Municipio("ETL", "99", "La Gomera"));
        municipios.add(new Municipio("ETL", "100", "Guaganazapa"));
        municipios.add(new Municipio("ETL", "101", "San José"));
        municipios.add(new Municipio("ETL", "102", "Iztapa"));
        municipios.add(new Municipio("ETL", "103", "Palín"));
        municipios.add(new Municipio("ETL", "104", "San Vicente Pacaya"));
        municipios.add(new Municipio("ETL", "105", "Nueva Concepción"));
        municipios.add(new Municipio("GTM", "106", "Santa Catarina Pinula"));
        municipios.add(new Municipio("GTM", "107", "San José Pinula"));
        municipios.add(new Municipio("GTM", "108", "Guatemala"));
        municipios.add(new Municipio("GTM", "109", "San José del Golfo"));
        municipios.add(new Municipio("GTM", "110", "Palencia"));
        municipios.add(new Municipio("GTM", "111", "Chinautla"));
        municipios.add(new Municipio("GTM", "112", "San Pedro Ayampuc"));
        municipios.add(new Municipio("GTM", "113", "Mixco"));
        municipios.add(new Municipio("GTM", "114", "San Pedro Sacatapéquez"));
        municipios.add(new Municipio("GTM", "115", "San Juan Sacatepéquez"));
        municipios.add(new Municipio("GTM", "116", "Chuarrancho"));
        municipios.add(new Municipio("GTM", "117", "San Raymundo"));
        municipios.add(new Municipio("GTM", "118", "Fraijanes"));
        municipios.add(new Municipio("GTM", "119", "Amatitlán"));
        municipios.add(new Municipio("GTM", "120", "Villa Nueva"));
        municipios.add(new Municipio("GTM", "121", "Villa Canales"));
        municipios.add(new Municipio("GTM", "122", "San Miguel Petapa"));
        municipios.add(new Municipio("HUE", "123", "Huehuetenango"));
        municipios.add(new Municipio("HUE", "124", "Chiantla"));
        municipios.add(new Municipio("HUE", "125", "Malacatancito"));
        municipios.add(new Municipio("HUE", "126", "Cuilco"));
        municipios.add(new Municipio("HUE", "127", "Nentón"));
        municipios.add(new Municipio("HUE", "128", "San Pedro Necta"));
        municipios.add(new Municipio("HUE", "129", "Jacaltenango"));
        municipios.add(new Municipio("HUE", "130", "Soloma"));
        municipios.add(new Municipio("HUE", "131", "Ixtahuacán"));
        municipios.add(new Municipio("HUE", "132", "Santa Bárbara"));
        municipios.add(new Municipio("HUE", "133", "La Libertad"));
        municipios.add(new Municipio("HUE", "134", "La Democracia"));
        municipios.add(new Municipio("HUE", "135", "San Miguel Acatán"));
        municipios.add(new Municipio("HUE", "136", "San Rafael La Independencia"));
        municipios.add(new Municipio("HUE", "137", "Todos Santos Cuchumatán"));
        municipios.add(new Municipio("HUE", "138", "San Juan Atitlán"));
        municipios.add(new Municipio("HUE", "139", "Santa Eulalia"));
        municipios.add(new Municipio("HUE", "140", "San Mateo Ixtatán"));
        municipios.add(new Municipio("HUE", "141", "Colotenango"));
        municipios.add(new Municipio("HUE", "142", "San Sebastián Huehuetenango"));
        municipios.add(new Municipio("HUE", "143", "Tectitán"));
        municipios.add(new Municipio("HUE", "144", "Concepción Huista"));
        municipios.add(new Municipio("HUE", "145", "San Juan Ixcoy"));
        municipios.add(new Municipio("HUE", "146", "San Antonio Huista"));
        municipios.add(new Municipio("HUE", "147", "Santa Cruz Barillas"));
        municipios.add(new Municipio("HUE", "148", "San Sebastián Coatán"));
        municipios.add(new Municipio("HUE", "149", "Aguacatán"));
        municipios.add(new Municipio("HUE", "150", "San Rafael Petzal"));
        municipios.add(new Municipio("HUE", "151", "San Gaspar Ixchil"));
        municipios.add(new Municipio("HUE", "152", "Santiago Chimaltenango"));
        municipios.add(new Municipio("HUE", "153", "Santa Ana Huista"));
        municipios.add(new Municipio("IZA", "154", "Morales"));
        municipios.add(new Municipio("IZA", "155", "Los Amates"));
        municipios.add(new Municipio("IZA", "156", "Livingston"));
        municipios.add(new Municipio("IZA", "157", "El Estor"));
        municipios.add(new Municipio("IZA", "158", "Puerto Barrios"));
        municipios.add(new Municipio("JLP", "159", "Jalapa"));
        municipios.add(new Municipio("JLP", "160", "San Pedro Pinula"));
        municipios.add(new Municipio("JLP", "161", "San Luis Jilotepeque"));
        municipios.add(new Municipio("JLP", "162", "San Manuel Chaparrón"));
        municipios.add(new Municipio("JLP", "163", "San Carlos Alzatate"));
        municipios.add(new Municipio("JLP", "164", "Monjas"));
        municipios.add(new Municipio("JLP", "165", "Mataquescuintla"));
        municipios.add(new Municipio("JTP", "166", "Jutiapa"));
        municipios.add(new Municipio("JTP", "167", "El Progreso"));
        municipios.add(new Municipio("JTP", "168", "Santa Catarina Mita"));
        municipios.add(new Municipio("JTP", "169", "Agua Blanca"));
        municipios.add(new Municipio("JTP", "170", "Asunción Mita"));
        municipios.add(new Municipio("JTP", "171", "Yupiltepeque"));
        municipios.add(new Municipio("JTP", "172", "Atescatempa"));
        municipios.add(new Municipio("JTP", "173", "Jerez"));
        municipios.add(new Municipio("JTP", "174", "El Adelanto"));
        municipios.add(new Municipio("JTP", "175", "Zapotitlán"));
        municipios.add(new Municipio("JTP", "176", "Comapa"));
        municipios.add(new Municipio("JTP", "177", "Jalpatagua"));
        municipios.add(new Municipio("JTP", "178", "Conguaco"));
        municipios.add(new Municipio("JTP", "179", "Moyuta"));
        municipios.add(new Municipio("JTP", "180", "Pasaco"));
        municipios.add(new Municipio("JTP", "181", "Quesada"));
        municipios.add(new Municipio("QTZ", "182", "Quetzaltenango"));
        municipios.add(new Municipio("QTZ", "183", "Salcajá"));
        municipios.add(new Municipio("QTZ", "184", "San Juan Olintepeque"));
        municipios.add(new Municipio("QTZ", "185", "San Carlos Sija"));
        municipios.add(new Municipio("QTZ", "186", "Sibilia"));
        municipios.add(new Municipio("QTZ", "187", "Cabricán"));
        municipios.add(new Municipio("QTZ", "188", "Cajolá"));
        municipios.add(new Municipio("QTZ", "189", "San Miguel Siguilá"));
        municipios.add(new Municipio("QTZ", "190", "San Juan Ostuncalco"));
        municipios.add(new Municipio("QTZ", "191", "San Mateo"));
        municipios.add(new Municipio("QTZ", "192", "Concepción Chiquirichapa"));
        municipios.add(new Municipio("QTZ", "193", "San Martín Sacatepéquez"));
        municipios.add(new Municipio("QTZ", "194", "Almolonga"));
        municipios.add(new Municipio("QTZ", "195", "Cantel"));
        municipios.add(new Municipio("QTZ", "196", "Huitán"));
        municipios.add(new Municipio("QTZ", "197", "Zunil"));
        municipios.add(new Municipio("QTZ", "198", "Colomba Costa Cuca"));
        municipios.add(new Municipio("QTZ", "199", "San Francisco La Unión"));
        municipios.add(new Municipio("QTZ", "200", "El Palmar"));
        municipios.add(new Municipio("QTZ", "201", "Coatepeque"));
        municipios.add(new Municipio("QTZ", "202", "Génova"));
        municipios.add(new Municipio("QTZ", "203", "Flores Costa Cuca"));
        municipios.add(new Municipio("QTZ", "204", "La Esperanza"));
        municipios.add(new Municipio("QTZ", "205", "Palestina de Los Altos"));
        municipios.add(new Municipio("RTL", "206", "Retalhuleu"));
        municipios.add(new Municipio("RTL", "207", "San Sebastián"));
        municipios.add(new Municipio("RTL", "208", "Santa Cruz Muluá"));
        municipios.add(new Municipio("RTL", "209", "San Martín Zapotitlán"));
        municipios.add(new Municipio("RTL", "210", "San Felipe"));
        municipios.add(new Municipio("RTL", "211", "San Andrés Villa Seca"));
        municipios.add(new Municipio("RTL", "212", "Champerico"));
        municipios.add(new Municipio("RTL", "213", "Nuevo San Carlos"));
        municipios.add(new Municipio("RTL", "214", "El Asintal"));
        municipios.add(new Municipio("STP", "215", "Antigua Guatemala"));
        municipios.add(new Municipio("STP", "216", "Jocotenango"));
        municipios.add(new Municipio("STP", "217", "Pastores"));
        municipios.add(new Municipio("STP", "218", "Sumpango"));
        municipios.add(new Municipio("STP", "219", "Santo Domingo Xenacoj"));
        municipios.add(new Municipio("STP", "220", "Santiago Sacatepéquez"));
        municipios.add(new Municipio("STP", "221", "San Bartolomé Milpas Altas"));
        municipios.add(new Municipio("STP", "222", "San Lucas Sacatepéquez"));
        municipios.add(new Municipio("STP", "223", "Santa Lucía Milpas Altas"));
        municipios.add(new Municipio("STP", "224", "Magdalena Milpas Altas"));
        municipios.add(new Municipio("STP", "225", "Santa María de Jesús"));
        municipios.add(new Municipio("STP", "226", "Ciudad Vieja"));
        municipios.add(new Municipio("STP", "227", "San Miguel Dueñas"));
        municipios.add(new Municipio("STP", "228", "San Juan Alotenango"));
        municipios.add(new Municipio("STP", "229", "San Antonio Aguas Calientes"));
        municipios.add(new Municipio("STP", "230", "Santa Catarina Barahona"));
        municipios.add(new Municipio("SNM", "231", "San Marcos"));
        municipios.add(new Municipio("SNM", "232", "Ayutla"));
        municipios.add(new Municipio("SNM", "233", "Catarina"));
        municipios.add(new Municipio("SNM", "234", "Comitancillo"));
        municipios.add(new Municipio("SNM", "235", "Concepción Tutuapa"));
        municipios.add(new Municipio("SNM", "236", "El Quetzal"));
        municipios.add(new Municipio("SNM", "237", "El Rodeo"));
        municipios.add(new Municipio("SNM", "238", "El Tumblador"));
        municipios.add(new Municipio("SNM", "239", "Ixchiguán"));
        municipios.add(new Municipio("SNM", "240", "La Reforma"));
        municipios.add(new Municipio("SNM", "241", "Malacatán"));
        municipios.add(new Municipio("SNM", "242", "Nuevo Progreso"));
        municipios.add(new Municipio("SNM", "243", "Ocós"));
        municipios.add(new Municipio("SNM", "244", "Pajapita"));
        municipios.add(new Municipio("SNM", "245", "Esquipulas Palo Gordo"));
        municipios.add(new Municipio("SNM", "246", "San Antonio Sacatepéquez"));
        municipios.add(new Municipio("SNM", "247", "San Cristóbal Cucho"));
        municipios.add(new Municipio("SNM", "248", "San José Ojetenam"));
        municipios.add(new Municipio("SNM", "249", "San Lorenzo"));
        municipios.add(new Municipio("SNM", "250", "San Miguel Ixtahuacán"));
        municipios.add(new Municipio("SNM", "251", "San Pablo"));
        municipios.add(new Municipio("SNM", "252", "San Pedro Sacatepéquez"));
        municipios.add(new Municipio("SNM", "253", "San Rafael Pie de la Cuesta"));
        municipios.add(new Municipio("SNM", "254", "Sibinal"));
        municipios.add(new Municipio("SNM", "255", "Sipacapa"));
        municipios.add(new Municipio("SNM", "256", "Tacaná"));
        municipios.add(new Municipio("SNM", "257", "Tajumulco"));
        municipios.add(new Municipio("SNM", "258", "Tejutla"));
        municipios.add(new Municipio("SNM", "259", "Río Blanco"));
        municipios.add(new Municipio("SNM", "260", "La Blanca"));
        municipios.add(new Municipio("STR", "261", "Cuilapa"));
        municipios.add(new Municipio("STR", "262", "Casillas Santa Rosa"));
        municipios.add(new Municipio("STR", "263", "Chiquimulilla"));
        municipios.add(new Municipio("STR", "264", "Guazacapán"));
        municipios.add(new Municipio("STR", "265", "Nueva Santa Rosa"));
        municipios.add(new Municipio("STR", "266", "Oratorio"));
        municipios.add(new Municipio("STR", "267", "Pueblo Nuevo Viñas"));
        municipios.add(new Municipio("STR", "268", "San Juan Tecuaco"));
        municipios.add(new Municipio("STR", "269", "San Rafael Las Flores"));
        municipios.add(new Municipio("STR", "270", "Santa Cruz Naranjo"));
        municipios.add(new Municipio("STR", "271", "Santa María Ixhuatán"));
        municipios.add(new Municipio("STR", "272", "Santa Rosa de Lima"));
        municipios.add(new Municipio("STR", "273", "Taxisco"));
        municipios.add(new Municipio("STR", "274", "Barberena"));
        municipios.add(new Municipio("SLA", "275", "Sololá"));
        municipios.add(new Municipio("SLA", "276", "Concepción"));
        municipios.add(new Municipio("SLA", "277", "Nahualá"));
        municipios.add(new Municipio("SLA", "278", "Panajachel"));
        municipios.add(new Municipio("SLA", "279", "San Andrés Semetabaj"));
        municipios.add(new Municipio("SLA", "280", "San Antonio Palopó"));
        municipios.add(new Municipio("SLA", "281", "San José Chacayá"));
        municipios.add(new Municipio("SLA", "282", "San Juan La Laguna"));
        municipios.add(new Municipio("SLA", "283", "San Lucas Tolimán"));
        municipios.add(new Municipio("SLA", "284", "San Marcos La Laguna"));
        municipios.add(new Municipio("SLA", "285", "San Pablo La Laguna"));
        municipios.add(new Municipio("SLA", "286", "San Pedro La Laguna"));
        municipios.add(new Municipio("SLA", "287", "Santa Catarina Ixtahuacán"));
        municipios.add(new Municipio("SLA", "288", "Santa Catarina Palopó"));
        municipios.add(new Municipio("SLA", "289", "Santa Clara La Laguna"));
        municipios.add(new Municipio("SLA", "290", "Santa Cruz La Laguna"));
        municipios.add(new Municipio("SLA", "291", "Santa Lucía Utatlán"));
        municipios.add(new Municipio("SLA", "292", "Santa María Visitación"));
        municipios.add(new Municipio("SLA", "293", "Santiago Atitlán"));
        municipios.add(new Municipio("STZ", "294", "Mazatenango"));
        municipios.add(new Municipio("STZ", "295", "Cuyotenango"));
        municipios.add(new Municipio("STZ", "296", "San Francisco Zapotitlán"));
        municipios.add(new Municipio("STZ", "297", "San Bernardino"));
        municipios.add(new Municipio("STZ", "298", "San José El Ídolo"));
        municipios.add(new Municipio("STZ", "299", "Santo Domingo Suchitépequez"));
        municipios.add(new Municipio("STZ", "300", "San Lorenzo"));
        municipios.add(new Municipio("STZ", "301", "Samayac"));
        municipios.add(new Municipio("STZ", "302", "San Pablo Jocopilas"));
        municipios.add(new Municipio("STZ", "303", "San Antonio Suchitépequez"));
        municipios.add(new Municipio("STZ", "304", "San Miguel Panán"));
        municipios.add(new Municipio("STZ", "305", "San Gabriel"));
        municipios.add(new Municipio("STZ", "306", "Chicacao"));
        municipios.add(new Municipio("STZ", "307", "Patulul"));
        municipios.add(new Municipio("STZ", "308", "Santa Bárbara"));
        municipios.add(new Municipio("STZ", "309", "San Juan Bautista"));
        municipios.add(new Municipio("STZ", "310", "Santo Tomás La Unión"));
        municipios.add(new Municipio("STZ", "311", "Zunilito"));
        municipios.add(new Municipio("STZ", "312", "Pueblo Nuevo"));
        municipios.add(new Municipio("STZ", "313", "Río Bravo"));
        municipios.add(new Municipio("TCN", "314", "Totonicapán"));
        municipios.add(new Municipio("TCN", "315", "San Cristóbal Totonicapán"));
        municipios.add(new Municipio("TCN", "316", "San Francisco El Alto"));
        municipios.add(new Municipio("TCN", "317", "San Andrés Xecul"));
        municipios.add(new Municipio("TCN", "318", "Momostenango"));
        municipios.add(new Municipio("TCN", "319", "Santa María Chiquimula"));
        municipios.add(new Municipio("TCN", "320", "Santa Lucía La Reforma"));
        municipios.add(new Municipio("TCN", "321", "San Bartolo"));
        municipios.add(new Municipio("ZAC", "322", "Cabañas"));
        municipios.add(new Municipio("ZAC", "323", "Estanzuela"));
        municipios.add(new Municipio("ZAC", "324", "Gualán"));
        municipios.add(new Municipio("ZAC", "325", "Huité"));
        municipios.add(new Municipio("ZAC", "326", "La Unión"));
        municipios.add(new Municipio("ZAC", "327", "Río Hondo"));
        municipios.add(new Municipio("ZAC", "328", "San Jorge"));
        municipios.add(new Municipio("ZAC", "329", "San Diego"));
        municipios.add(new Municipio("ZAC", "330", "Teculután"));
        municipios.add(new Municipio("ZAC", "331", "Usumatlán"));
        municipios.add(new Municipio("ZAC", "332", "Zacapa"));
    }

}
