/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author Fernando
 */
public class DashboardAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form DashboardAdministrador
     */
    public DashboardAdministrador() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lblFotoPerfil = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        lblRol = new javax.swing.JLabel();
        btnReportes = new javax.swing.JButton();
        btnKioscos = new javax.swing.JButton();
        btnRegiones = new javax.swing.JButton();
        btnDepYMuni = new javax.swing.JButton();
        btnNuevoUsuario = new javax.swing.JButton();
        btnReportes1 = new javax.swing.JButton();
        container = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblNombreEmpresa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard administrador");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPrincipal.setBackground(new java.awt.Color(38, 70, 83));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFotoPerfil.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblFotoPerfil.setForeground(new java.awt.Color(241, 250, 238));
        lblFotoPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profilePhoto.png"))); // NOI18N
        lblFotoPerfil.setText("Irving Alvarado");
        lblFotoPerfil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblFotoPerfil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlPrincipal.add(lblFotoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnCerrarSesion.setBackground(new java.awt.Color(38, 70, 83));
        btnCerrarSesion.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(241, 250, 238));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setContentAreaFilled(false);
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 120, 30));

        lblRol.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 10)); // NOI18N
        lblRol.setForeground(new java.awt.Color(241, 250, 238));
        lblRol.setText("Adminstrador");
        pnlPrincipal.add(lblRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        btnReportes.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(241, 250, 238));
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reportes.png"))); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 8, 12, 8));
        btnReportes.setBorderPainted(false);
        btnReportes.setContentAreaFilled(false);
        btnReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReportes.setHideActionText(true);
        btnReportes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReportes.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 140, 40));

        btnKioscos.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        btnKioscos.setForeground(new java.awt.Color(241, 250, 238));
        btnKioscos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kiosco.png"))); // NOI18N
        btnKioscos.setText("Kioscos");
        btnKioscos.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 8, 12, 8));
        btnKioscos.setBorderPainted(false);
        btnKioscos.setContentAreaFilled(false);
        btnKioscos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKioscos.setHideActionText(true);
        btnKioscos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnKioscos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnKioscos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKioscosActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnKioscos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 136, 140, 40));

        btnRegiones.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        btnRegiones.setForeground(new java.awt.Color(241, 250, 238));
        btnRegiones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/regiones.png"))); // NOI18N
        btnRegiones.setText("Regiones");
        btnRegiones.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 8, 12, 8));
        btnRegiones.setBorderPainted(false);
        btnRegiones.setContentAreaFilled(false);
        btnRegiones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegiones.setHideActionText(true);
        btnRegiones.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegiones.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnRegiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegionesActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnRegiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 140, 40));

        btnDepYMuni.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        btnDepYMuni.setForeground(new java.awt.Color(241, 250, 238));
        btnDepYMuni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mapa.png"))); // NOI18N
        btnDepYMuni.setText("Dep. y Muni.");
        btnDepYMuni.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 8, 12, 8));
        btnDepYMuni.setBorderPainted(false);
        btnDepYMuni.setContentAreaFilled(false);
        btnDepYMuni.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDepYMuni.setHideActionText(true);
        btnDepYMuni.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDepYMuni.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDepYMuni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepYMuniActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnDepYMuni, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 140, 40));

        btnNuevoUsuario.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        btnNuevoUsuario.setForeground(new java.awt.Color(241, 250, 238));
        btnNuevoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usuarioNuevo.png"))); // NOI18N
        btnNuevoUsuario.setText("Crear usuario");
        btnNuevoUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 8, 12, 8));
        btnNuevoUsuario.setBorderPainted(false);
        btnNuevoUsuario.setContentAreaFilled(false);
        btnNuevoUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevoUsuario.setHideActionText(true);
        btnNuevoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNuevoUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoUsuarioActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnNuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 140, 40));

        btnReportes1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        btnReportes1.setForeground(new java.awt.Color(241, 250, 238));
        btnReportes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usuarios.png"))); // NOI18N
        btnReportes1.setText("Usuarios");
        btnReportes1.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 8, 12, 8));
        btnReportes1.setBorderPainted(false);
        btnReportes1.setContentAreaFilled(false);
        btnReportes1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReportes1.setHideActionText(true);
        btnReportes1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReportes1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnReportes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportes1ActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnReportes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 140, 40));

        getContentPane().add(pnlPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 480));

        container.setBackground(new java.awt.Color(241, 250, 238));
        container.setMinimumSize(new java.awt.Dimension(740, 480));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/camion.png"))); // NOI18N

        lblNombreEmpresa.setBackground(new java.awt.Color(37, 36, 34));
        lblNombreEmpresa.setFont(new java.awt.Font("Montserrat", 1, 28)); // NOI18N
        lblNombreEmpresa.setForeground(new java.awt.Color(38, 70, 83));
        lblNombreEmpresa.setText("USAC - Delivery");

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(lblLogo))
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(lblNombreEmpresa))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(lblLogo)
                .addGap(2, 2, 2)
                .addComponent(lblNombreEmpresa))
        );

        getContentPane().add(container, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 740, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rellenarPanel(JPanel panel, String nombre) {

        panel.setSize(740, 480);
        panel.setLocation(0, 0);

        container.removeAll();
        container.add(panel, BorderLayout.CENTER);
        container.revalidate();
        container.repaint();
        this.setTitle(nombre);
    }

    Login login = new Login();
    Kioscos kioscos = new Kioscos();
    Regiones regiones = new Regiones();
    Reportes reportes = new Reportes();
    Usuarios usuarios = new Usuarios();


    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnKioscosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKioscosActionPerformed
        rellenarPanel(kioscos, "Administracion de kioscos");
        kioscos.cargarLista();
        kioscos.limpiarCampos();
    }//GEN-LAST:event_btnKioscosActionPerformed

    private void btnRegionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegionesActionPerformed
        rellenarPanel(regiones, "Administracion de regiones");
        regiones.cargarLista();
        regiones.limpiarCampos();
    }//GEN-LAST:event_btnRegionesActionPerformed

    private void btnDepYMuniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepYMuniActionPerformed
        MenuDepartamentosYMunicipios menu = new MenuDepartamentosYMunicipios();
        rellenarPanel(menu, "Administracion de departamentos y municipios");
    }//GEN-LAST:event_btnDepYMuniActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        rellenarPanel(reportes, "Reportes");
        reportes.ordenarRegiones();
        reportes.ordenarUsuarios();
        reportes.cargarListaRegiones();
        reportes.cargarListaUsuarios();
        reportes.cargarCamposDeTexto();
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoUsuarioActionPerformed
        RegistrarUsuario registrar = new RegistrarUsuario();
        registrar.setVisible(true);
    }//GEN-LAST:event_btnNuevoUsuarioActionPerformed

    
    private void btnReportes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportes1ActionPerformed
        rellenarPanel(usuarios, "Administración de usuarios");
        usuarios.cargarListaUsuarios();
    }//GEN-LAST:event_btnReportes1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnDepYMuni;
    private javax.swing.JButton btnKioscos;
    private javax.swing.JButton btnNuevoUsuario;
    private javax.swing.JButton btnRegiones;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnReportes1;
    public javax.swing.JPanel container;
    private javax.swing.JLabel lblFotoPerfil;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNombreEmpresa;
    private javax.swing.JLabel lblRol;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
