/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author Fernando
 */
public class MenuDepartamentosYMunicipios extends javax.swing.JPanel {

    /**
     * Creates new form MenuDepartamentosYMunicipios
     */
    public MenuDepartamentosYMunicipios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        btnMunicipios = new javax.swing.JButton();
        btnDepartamentos = new javax.swing.JButton();

        container.setBackground(new java.awt.Color(241, 250, 238));

        btnMunicipios.setBackground(new java.awt.Color(38, 70, 83));
        btnMunicipios.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnMunicipios.setForeground(new java.awt.Color(241, 250, 238));
        btnMunicipios.setText("Administrar Municipios");
        btnMunicipios.setBorderPainted(false);
        btnMunicipios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMunicipios.setFocusPainted(false);
        btnMunicipios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMunicipiosActionPerformed(evt);
            }
        });

        btnDepartamentos.setBackground(new java.awt.Color(38, 70, 83));
        btnDepartamentos.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnDepartamentos.setForeground(new java.awt.Color(241, 250, 238));
        btnDepartamentos.setText("Administrar Departamentos");
        btnDepartamentos.setBorderPainted(false);
        btnDepartamentos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDepartamentos.setFocusPainted(false);
        btnDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepartamentosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btnDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnMunicipios, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMunicipios, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    void rellenarPanel(JPanel panel) {
        panel.setSize(740, 480);
        panel.setLocation(0, 0);

        container.removeAll();
        container.add(panel, BorderLayout.CENTER);
        container.revalidate();
        container.repaint();
    }
   
    private void btnDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepartamentosActionPerformed
        Departamentos dep = new Departamentos();
        rellenarPanel(dep);
    }//GEN-LAST:event_btnDepartamentosActionPerformed

    private void btnMunicipiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMunicipiosActionPerformed
        Municipios muni = new Municipios();
        rellenarPanel(muni);
    }//GEN-LAST:event_btnMunicipiosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDepartamentos;
    private javax.swing.JButton btnMunicipios;
    private javax.swing.JPanel container;
    // End of variables declaration//GEN-END:variables
}
