/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import Datos.AlmacenamientoDeDatos;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Departamento;
import modelo.Municipio;

/**
 *
 * @author Fernando
 */
public class Municipios extends javax.swing.JPanel {

    /**
     * Creates new form KioscosV2
     */
    public Municipios() {
        initComponents();
        cargarDepartamentos();
        cargarLista();
        cargarPrimerElemento();
    }

    AlmacenamientoDeDatos datos = new AlmacenamientoDeDatos();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreDepto = new javax.swing.JLabel();
        txtNombreDepto = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblCodigoDepto = new javax.swing.JLabel();
        lstDepartamentos = new javax.swing.JComboBox<>();
        btnAñadir = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMunicipios = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();
        lblCodigoMunicipio = new javax.swing.JLabel();
        txtCodigoMunicipio = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblNombreMunicipio = new javax.swing.JLabel();
        txtNombreMunicipio = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(241, 250, 238));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreDepto.setBackground(new java.awt.Color(34, 34, 59));
        lblNombreDepto.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        lblNombreDepto.setForeground(new java.awt.Color(34, 34, 59));
        lblNombreDepto.setText("Nombre del Depto:");
        add(lblNombreDepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        txtNombreDepto.setBackground(new java.awt.Color(241, 250, 238));
        txtNombreDepto.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtNombreDepto.setForeground(new java.awt.Color(34, 34, 59));
        txtNombreDepto.setBorder(null);
        txtNombreDepto.setEnabled(false);
        add(txtNombreDepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 160, 30));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 160, 20));

        lblCodigoDepto.setBackground(new java.awt.Color(34, 34, 59));
        lblCodigoDepto.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        lblCodigoDepto.setForeground(new java.awt.Color(34, 34, 59));
        lblCodigoDepto.setText("Código del departamento:");
        add(lblCodigoDepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        lstDepartamentos.setBackground(new java.awt.Color(241, 250, 238));
        lstDepartamentos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lstDepartamentosItemStateChanged(evt);
            }
        });
        add(lstDepartamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 110, -1));

        btnAñadir.setBackground(new java.awt.Color(38, 70, 83));
        btnAñadir.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        btnAñadir.setForeground(new java.awt.Color(241, 250, 238));
        btnAñadir.setText("Añadir");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });
        add(btnAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 100, 30));

        btnActualizar.setBackground(new java.awt.Color(38, 70, 83));
        btnActualizar.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(241, 250, 238));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 100, 30));

        btnEliminar.setBackground(new java.awt.Color(38, 70, 83));
        btnEliminar.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(241, 250, 238));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 100, 30));

        jScrollPane2.setBackground(new java.awt.Color(241, 250, 238));
        jScrollPane2.setForeground(new java.awt.Color(34, 34, 59));

        tblMunicipios.setBackground(new java.awt.Color(237, 237, 233));
        tblMunicipios.setForeground(new java.awt.Color(34, 34, 59));
        tblMunicipios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblMunicipios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMunicipiosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMunicipios);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 600, 160));

        lblTitulo.setBackground(new java.awt.Color(37, 36, 34));
        lblTitulo.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(38, 70, 83));
        lblTitulo.setText("Municipios");
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        lblCodigoMunicipio.setBackground(new java.awt.Color(34, 34, 59));
        lblCodigoMunicipio.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        lblCodigoMunicipio.setForeground(new java.awt.Color(34, 34, 59));
        lblCodigoMunicipio.setText("Codigo del municipio:");
        add(lblCodigoMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        txtCodigoMunicipio.setBackground(new java.awt.Color(241, 250, 238));
        txtCodigoMunicipio.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtCodigoMunicipio.setForeground(new java.awt.Color(34, 34, 59));
        txtCodigoMunicipio.setBorder(null);
        add(txtCodigoMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 150, 30));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 150, 20));

        lblNombreMunicipio.setBackground(new java.awt.Color(34, 34, 59));
        lblNombreMunicipio.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        lblNombreMunicipio.setForeground(new java.awt.Color(34, 34, 59));
        lblNombreMunicipio.setText("Nombe del municipio:");
        add(lblNombreMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        txtNombreMunicipio.setBackground(new java.awt.Color(241, 250, 238));
        txtNombreMunicipio.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtNombreMunicipio.setForeground(new java.awt.Color(34, 34, 59));
        txtNombreMunicipio.setBorder(null);
        add(txtNombreMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 150, 30));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 150, 20));

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void lstDepartamentosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lstDepartamentosItemStateChanged
        txtNombreDepto.setText(obtenerNombreDepartamento(lstDepartamentos.getSelectedItem().toString()));
    }//GEN-LAST:event_lstDepartamentosItemStateChanged

    private void tblMunicipiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMunicipiosMouseClicked
        int fila = tblMunicipios.getSelectedRow();
        txtCodigoMunicipio.setText(tblMunicipios.getValueAt(fila, 1).toString());
        txtNombreMunicipio.setText(tblMunicipios.getValueAt(fila, 2).toString());
    }//GEN-LAST:event_tblMunicipiosMouseClicked

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        String codigoDepartamento;
        if (lstDepartamentos.getSelectedItem() != null) {
            codigoDepartamento = lstDepartamentos.getSelectedItem().toString();
        } else {
            codigoDepartamento = "NOEXISTE";
        }

        String codigoMunicipio = txtCodigoMunicipio.getText();
        String nombreMunicipio = txtNombreMunicipio.getText();

        if (codigoDepartamento.isEmpty() || codigoMunicipio.isEmpty() || nombreMunicipio.isEmpty()) {

            JOptionPane.showMessageDialog(null, "Todos los campos deben estar llenos");

        } else if (lstDepartamentos.getSelectedItem() == null) {

            JOptionPane.showMessageDialog(null, "Antes de crear un municipio, debe crear al menos un departamento");

        } else {

            boolean existe = false;

            for (Municipio municipio : datos.municipios) {

                if (municipio.getCodigoMunicipio().equals(codigoMunicipio)) {
                    existe = true;
                    break;
                }
            }

            if (existe == true) {
                JOptionPane.showMessageDialog(null, "El codigo del municipio ya se encuentran registrado, revise sus datos");
            } else {

                datos.municipios.add(new Municipio(codigoDepartamento, codigoMunicipio, nombreMunicipio));
                cargarLista();
                limpiarCampos();

                JOptionPane.showMessageDialog(null, "Municipio agregado correctamente");
            }

        }
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        String codigoDepartamento;
        if (lstDepartamentos.getSelectedItem() != null) {
            codigoDepartamento = lstDepartamentos.getSelectedItem().toString();
        } else {
            codigoDepartamento = "NOEXISTE";
        }

        String codigoMunicipio = txtCodigoMunicipio.getText();
        String nombreMunicipio = txtNombreMunicipio.getText();

        if (codigoDepartamento.isEmpty() || codigoMunicipio.isEmpty() || nombreMunicipio.isEmpty()) {

            JOptionPane.showMessageDialog(null, "Todos los campos deben estar llenos");

        } else if (lstDepartamentos.getSelectedItem() == null) {

            JOptionPane.showMessageDialog(null, "Debe haber un departamento para actualizar los municipios de esa region");

        } else {

            boolean existe = false;

            for (Municipio municipio : datos.municipios) {
                if (municipio.getCodigoMunicipio().equals(codigoMunicipio)) {

                    existe = true;
                    municipio.setCodigoDepartamento(codigoDepartamento);
                    municipio.setNombreMunicipio(nombreMunicipio);
                    break;
                }
            }

            if (existe == true) {
                JOptionPane.showMessageDialog(null, "Se actualizó el municipio con el codigo " + codigoMunicipio);
                cargarLista();
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró ningun municipio con el codigo " + codigoMunicipio + "\nAsegurese de que en el campo Codigo Municipio se encuentre el codigo del municipio que desea actualizar");
            }

        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String codigoMunicipio = txtCodigoMunicipio.getText();

        if (codigoMunicipio.isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo codigo municipio debe contener el codigo del municipio que desea eliminar");
        } else {
            int respuesta = JOptionPane.showConfirmDialog(null, "Esta seguro de que desea eliminar el municipio con el codigo " + codigoMunicipio, "Confirmación de eliminación", JOptionPane.YES_NO_OPTION);
            if (respuesta == JOptionPane.YES_OPTION) {
                
                boolean existe = false;
                Iterator<Municipio> iter = datos.municipios.iterator();
                while (iter.hasNext()) {
                    Municipio municipio = iter.next();
                    if (municipio.getCodigoMunicipio().equals(codigoMunicipio)) {
                        existe = true;
                        iter.remove();
                        break;
                    }
                }
                if (existe) {
                    JOptionPane.showMessageDialog(null, "Se eliminó el municipio con el codigo " + codigoMunicipio);
                    cargarLista();
                    limpiarCampos();
                } else {
                    JOptionPane.showMessageDialog(null, "No se encontró ningun municipio con el codigo " + codigoMunicipio + "\nAsegurese de que en el campo Codigo municipio se encuentre el codigo del municipio que desea eliminar");
                }
            } else {
                JOptionPane.showMessageDialog(null, "No se eliminará el municipio");
            }
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    void limpiarCampos() {
        txtCodigoMunicipio.setText("");
        txtNombreMunicipio.setText("");
    }

    void cargarDepartamentos() {

        for (Departamento departamento : datos.departamentos) {
            lstDepartamentos.addItem(departamento.getCodigoDepartamento());
        }

    }

    String obtenerNombreDepartamento(String codigoDepartamento) {
        String nombreDepartamento = "";
        for (Departamento departamento : datos.departamentos) {

            if (departamento.getCodigoDepartamento().equals(codigoDepartamento)) {
                nombreDepartamento = departamento.getNombreDepartamento();
                break;
            }
        }

        return nombreDepartamento;
    }

    void cargarPrimerElemento() {
        if (lstDepartamentos.getSelectedItem() != null) {
            txtNombreDepto.setText(obtenerNombreDepartamento(lstDepartamentos.getSelectedItem().toString()));
        } else {

            txtNombreDepto.setText("-Vacio-");

        }
    }

    void cargarLista() {

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Codigo de departamento");
        modelo.addColumn("Codigo del municipio");
        modelo.addColumn("Nombre del municipio");

        for (Municipio municipio : datos.municipios) {

            Object[] fila = {municipio.getCodigoDepartamento(), municipio.getCodigoMunicipio(), municipio.getNombreMunicipio()};
            modelo.addRow(fila);

        }

        tblMunicipios.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblCodigoDepto;
    private javax.swing.JLabel lblCodigoMunicipio;
    private javax.swing.JLabel lblNombreDepto;
    private javax.swing.JLabel lblNombreMunicipio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JComboBox<String> lstDepartamentos;
    private javax.swing.JTable tblMunicipios;
    private javax.swing.JTextField txtCodigoMunicipio;
    private javax.swing.JTextField txtNombreDepto;
    private javax.swing.JTextField txtNombreMunicipio;
    // End of variables declaration//GEN-END:variables
}
