/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Fernando
 */
public class PanelDefault extends javax.swing.JPanel {

    /**
     * Creates new form PanelDefault
     */
    public PanelDefault() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        lblNombreEmpresa = new javax.swing.JLabel();

        setBackground(new java.awt.Color(241, 250, 238));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/camion.png"))); // NOI18N

        lblNombreEmpresa.setBackground(new java.awt.Color(37, 36, 34));
        lblNombreEmpresa.setFont(new java.awt.Font("Montserrat", 1, 28)); // NOI18N
        lblNombreEmpresa.setForeground(new java.awt.Color(38, 70, 83));
        lblNombreEmpresa.setText("USAC - Delivery");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(lblLogo))
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(lblNombreEmpresa))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(lblLogo)
                .addGap(2, 2, 2)
                .addComponent(lblNombreEmpresa))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNombreEmpresa;
    // End of variables declaration//GEN-END:variables
}
